# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1184965873);
user_pref("app.update.lastUpdateTime.background-update-timer", 1184965873);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1184965873);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1184965873);
user_pref("browser.bookmarks.sort.resource", "rdf:http://home.netscape.com/NC-rdf#URL");
user_pref("browser.download.lastDir", "/home/cc/images");
user_pref("browser.download.manager.showWhenStarting", false);
user_pref("browser.feeds.showFirstRunUI", false);
user_pref("browser.history_expire_days.mirror", 9);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.search.update", false);
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.startup.homepage", "file:///home/cc/index.html");
user_pref("browser.startup.homepage_override.mstone", "rv:1.8.1.4");
user_pref("extensions.lastAppVersion", "2.0.0.4");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8, ISO-8859-2, us-ascii");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pref.advanced.javascript.disable_button.advanced", false);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_leaving_secure", false);
user_pref("security.warn_submit_insecure", false);
user_pref("spellchecker.dictionary", "en-US");
user_pref("urlclassifier.tableversion.goog-black-url", "1.12699");
user_pref("urlclassifier.tableversion.goog-white-domain", "1.23");
user_pref("urlclassifier.tableversion.goog-white-url", "1.371");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
